
const Disclaimer = () => {
  return (
    <div className="bg-gray-100 p-4 rounded-md shadow-sm">
      <h3 className="text-lg font-medium text-gray-900">Important Disclaimer</h3>
      <p className="text-base text-gray-700">
        Please Note : TRADING IN STOCK MARKET IS INHERENTLY RISKY AND THE USERS AGREE TO TAKE COMPLETE AND FULL RESPONSIBILITY FOR THE OUTCOMES OF ALL 
        TRADING DECISIONS THAT THEY MAKE, INCLUDING BUT NOT LIMITED TO LOSS OF CAPITAL. THE SEBI REGISTERED 
        INTERMEDIARIES/EXPERTS MAY DISSEMINATE THEIR ANALYSIS, RESEARCH REPORTS AND RECOMMENDATIONS BY USING THE SERVICES PROVIDED 
        BY THE COMPANY AND THE WEBSITE WHICH MAY INCLUDE SMS OR E-MAIL COMMUNICATIONS, OR MAY ASK THE COMPANY, 
        OR ANY OF THE EMPLOYEEES OF SUCH COMPANIES TO DISSEMINATE SUCH INFORMATION ON THEIR BEHALF. 
        NONE OF THESE COMMUNICATIONS SHOULD BE CONSTRUED AS AN OFFER TO BUY OR SELL SECURITIES, 
        NOR ADVICE TO DO SO. ALL RECOMMENDATIONS MADE BY THE COMPANY AND THEIR EMPLOYEES/OWNERS
        ARE FOR INFORMATION PURPOSES ONLY AND UNDER NO CIRCUMSTANCES SHOULD BE USED AS THE BASIS FOR ACTUAL TRADING. 
        UNDER NO CIRCUMSTANCES SHOULD ANY USER MAKE TRADING DECISIONS BASED SOLELY ON THE INFORMATION AVAILABLE ON THE WEBSITE. 
        THE COMPANY IS NOT ACTING AS A QUALIFIED FINANCIAL ADVISOR AND THE USERS SHOULD NOT CONSTRUE ANY INFORMATION DISCUSSED ON THE WEBSITE TO CONSTITUTE INVESTMENT ADVICE. 
        IT IS INFORMATIONAL IN NATURE.
      </p>
      <p className="text-sm text-gray-500 mt-4">
        For more information about the company terms & conditions, Kindly visit our company website – https://twmresearchalert.com/
      </p>
    </div>
  )
}

export default Disclaimer