
const Userconsent = () => {
  return (
    <div>
        <h1>
                User Consent
        </h1>
        <p>
         By visiting/Using/accessing our website (https://twmresearchalert.com/) and/or our official mobile application and by making payment for a subscription of any of our research services, you are agreeing to be bound by the following terms and conditions and all other terms and conditions, Legal Disclaimer, Disclosures, Policies and User Consent of TWM Research Alert firm mentioned on our official website (https://twmresearchalert.com/).        </p>
        <p>
        We may change these terms and conditions and all other terms and conditions, Legal Disclaimer, Disclosures, Policies, and User Consent, at any time. Your continued use of our website and/or our mobile application and subscription to any of our research services means that you accept any new or modified terms and conditions and all other terms and conditions, Legal Disclaimer, Disclosures, Policies, and User Consent that we come up with. Please re-visit the `Terms and Conditions, ‘Legal Disclaimer’, ‘Disclosure’, ‘User Consent’, ‘Refund Policy’, and ‘Privacy Policy’ links on our website from time to time to stay abreast of any changes that we may introduce.
        </p>
        <p>
        The term TWM Research Alert firm (https://twmresearchalert.com/) is used throughout this entire document to refer to the website and/or our mobile application, its owners/proprietor, and the employees and associates of the owner. The words ‘You’ refer to the viewer/user/subscriber of TWM Research Alert firm website/mobile application/research services
        </p>
        <p>
        You hereby declare that the details provided by you at the time of subscription to our services are true and correct to the best of your knowledge and belief and you undertake to inform you of any changes therein, in case any of the above information is found to be false or misleading, you are aware that you may be held liable for it.
        You understand and accept that trading is a risky activity that involves the risk of loss of partial or complete capital and that there is no guarantee of profits or returns after subscribing to any of TWM Research Alert research alerts services.
        You understand and accept that the service provided by TWM Research Alert is general trading technical analysis research and is not investment The final decision to take or not to take any trade is completely yours. Also, the decision to trade the quantity of stocks/ FNO lots to be traded by referring to our research recommendation/alerts will also be completely yours. You accept the entire responsibility for any gains or losses that arise out of your trading activities.
        You understand and agree that TWM Research Alert Research Analyst firm and/or its owner/proprietor/managers/employees/associates do not provide any assurance or guarantee of accuracy or consistency of any our research alerts/service. Any accuracy level communicated to the user either in written or verbal or in our advertisements/website/mobile application, is merely for indicative purpose only. You understand and agree that the accuracy level/percentage of any of our research services/alerts may vary from time to time and there is no commitment from TWM Research Alert Research Analyst firm and/or its owner/proprietor/managers/employees/associates to deliver you research services/alerts with a fixed accuracy level/percentage.
        You understand that for any/all trades taken by you, you will be held responsible for the outcome of the trade/investment either resulting in a gain or You are willing to take complete responsibility for the outcome of all the trades placed in your Demat account/ trading account (Broker Account) during your tenure of the TWM Research Alert firms research service subscription period.
        You understand that the service provided by TWM Research Alert firm is only a research service and is meant only for reference. You understand and accept that the service provided by TWM Research Alert firm is not an Investment Advice and all decisions to trade/invest in any stock/ instrument are solely yours and any loss/ gain that may arise out of such trades/ investments are solely your responsibility/ liability.
        You Agree to All Terms and Conditions, Disclosures, Disclaimers, Policies, and User Consent of TWM Research Alert firm and You know Very Well About the Risk Associated with Trading & Investing in the Stock Market and still you wish to subscribe to the research services of the TWM Research Alert You have been informed completely about all the aspects of the services provided by TWM Research Alert firm including the risks associated with trading and investing in the Stock Market. You confirm and agree that You have taken the subscription of research services of TWM Research Alert firm after fully understanding the risks involved in Trading and Investing. You confirm and accept that You do not expect a fixed return or a guaranteed return from the research alerts service subscribed by you and you fully understand that you can/ might lose your partial or entire capital in trading & investing by referring to research services/ reports/ alerts of TWM Research Alert Firm.
        You have read and accepted all terms & conditions, legal disclaimer, Refund Policy, Privacy Policy, and User Consent of TWM Research Alert firm mentioned on our official website having domain name https://twmresearchalert.com/.
        And You have read, understood, and accepted the risk mentioned in the disclaimer on the website/mobile app of TWM Research Alert firm https://twmresearchalert.com/.
        You understand and accept that Trading in the stock market is subject to market risk and You understand and accept that You may lose some or your entire capital of yours in the stock market trading/ investing activities, therefore, TWM Research Alert firm or its the proprietor/owner cannot be held responsible for any losses in the stock market that you may incur and managing of trades is completely your responsibility. You confirm that You have not been asked for your Demat/ Trading Account Login ID & Password by any of the employees/representatives of TWM Research Alert Firm or anyone associated with TWM Research Alert Firm and your Demat/ Trading Account Login Credentials are not disclosed/Known to anyone except yourself.
        You understand and accept that You have been informed sufficiently of the risks of trading/investing in the stock market and You have still decided to take the subscription of TWM Research Alert trading research alerts services.
        You declare that You will be trading/ investing with your own personal capital and you will not be trading/investing with capital that has taken on a loan or capital belonging to someone other than yourself.
        You understand and accept that because You have been informed about all the risks in trading/investing and have taken the subscription package of TWM Research Alert trading research services/alerts, you have to bear the loss that may arise due to your trading activities. You also understand and accept that You cannot claim or complain against TWM Research Alert firm or its proprietor/ owner/ employees/ associates if you lose money in trading or investing.
        You declare that TWM Research Alert firm and its proprietor/ Owner/ employees/ associates have not guaranteed you or assured you any returns or profits by trading and investing in the stock
        You understand and accept that TWM Research Alert firm and its proprietor/owner/employees/ associates do not provide any order execution services for trading/ investing purposes.
        You understand and accept that Amount paid to TWM Research Alert firm are fees for providing you with a research alerts service and this amount is not an investment in the Stock Market itself and that the amount of the fee paid by you is not refundable in any conditions or You Understand and accept that the fees paid by you are only for research services and that the TWM Research Alert firm and it’s the proprietor/ Owner/ employees/ associates will not invest any amount on your behalf in the stock market and you have been informed clearly about the same by the employees/ representatives/ associates of TWM Research Alert Firm. You agree and accept that as you have understood and agreed to the take the risks involved in Trading/ Investing and that any loss that might arise out of any such trading activity done by you whether or not by reference to TWM Research Alert Firm research recommendation or call guidance, hence, you accept that you cannot and will not file any legal complaint or legal notice against the TWM Research Alert Firm and its proprietor/ Owner/ employees/ associates.
        You accept that you have read all the text in this document carefully in detail and you have understood and accepted all the mentioned terms and conditions as well as all the terms and conditions including all the disclaimers, disclosures, and policies mentioned in the official website of TWM Research Alert firm (https://twmresearchalert.com/). You officially accept all the terms and conditions laid by TWM Research Alert firm in a digital confirmation/consent via this document, the confirmation/consent provided by you may act as final notification & confirmation and it implies that you have understood and accepted all the risks involved in the trading/ investing activity in the stock market.
        </p>
        <p>
        We request you to acknowledge and confirm all the terms and conditions mentioned above in this document by clicking on the “Yes I Agree” button below in this document. TWM Research Alert Firm will consider these details and your consent/ acceptance of all the above terms and conditions to be final and will be taken on an as-is basis for all our services and products to which you may subscribe with us. On receipt or non-receipt of your confirmation to the Terms and Conditions of the above document, the above consent/ confirmation will be considered true and will be used in all our active records.
        </p>


    </div>
  )
}

export default Userconsent